### ISSUE TITLE
Querying recovery MPECs for apparent magnitude

### ISSUE THREAD

**Issue by rlseaman** [Yeqzids/mpecwatch#50]
Howdy!

We're about to submit a faint two-night recovery for a 2017 PHA. These are Gemini South observations at V > 25 and we're wondering what other faint NEO recovery MPECs have been published. There have been a number of faint TNO MPECs submitted recently, presumably in support of New Horizons, but not recoveries and not NEOs.

Does MPECWatch have a way to create such queries? Any other thoughts?

Thanks!

Rob

**Comment by Yeqzids** [comment]
MPEC Watch does not current store information of individual objects... It is a planned/request feature but it will likely take a while to implement. Have you tried [MPC's MPEC search tool](https://minorplanetcenter.net/mpcops/mpecs/)?

**Comment by Yeqzids** [comment]
Closing this one... Rob, feel free to reopen it as needed.
